server:
  port: 8080
  servlet:
    context-path: /api

app:
  qr:
    public-base-url: ""

spring:
  application:
    name: wechat-tools-backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  task:
    scheduling:
      pool:
        size: 2

storage:
  local:
    base-path: storage

file:
  cleanup:
    enabled: true
    max-age-hours: 24

baidu:
  ocr:
    app-id: "123037453"
    api-key: "ZJYL89aGvJPhOIcBYK9Js2AT"
    secret-key: "DAaH0xXJ40avLUuPuz5NdvqH2spkbSKC"
    enabled: true # 默认关闭，配置好密钥后改为 true
  image-matting:
    api-key: "X5dKDXnuWK7pzDHlaSjpueyJ"
    secret-key: "JfCgaA67CS2mIp5Q3wJttP8ZmAC3Bl8u"
    enabled: true

pdfcpu:
  enabled: true
  binary-path: ""
  timeout-seconds: 60

tencent:
  cos:
    secret-id: AKIDytc7NN8j6E7kPxJ3ZtzqTsCKH0UjvvgC
    secret-key: Jzvq0EQc6jTINVr0uZzA5yc1B6mCzsrl
    region: "ap-guangzhou"
    bucket: "my-word-pdf-1319429734"
  ci:
    queue-id: "p971a5f4111324d53a52234c384c5ab91"
    input-prefix: ci/input/
    output-prefix: ci/output/
    poll-interval-millis: 2000
    timeout-seconds: 180
    keep-remote-files: false
